[package]
name = "zk-snarks-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bellman = {version = "0.11.1", features = ["groth16"]}
bls12_381 = "0.6"
rand = "0.8"
ff = "0.11"